version: '3.5'
name: backend   

networks:
  backend:
    driver: bridge
  # web_frontend:
  #   external: true
  elastic:
    driver: bridge
  monitoring:
    driver: bridge
     
services:   

  proxy:
    container_name: Nginx-proxy
    image: nginx:mainline
    depends_on:
      - storage.api
    networks:
      - backend

  aggregator.api:
    container_name: microservice_Aggregator-api
    image: ${DOCKER_REGISTRY-}aggregatorapi
    volumes:
      - ./../Aggregator.DataAccess/Scripts:/root/app
    build:
      context: .
      dockerfile: Services/Aggregator/Aggregator.Api/Dockerfile
    networks:
      - backend
    environment:
      - Otel__Endpoint=http://otel-collector:4317
      - DB_HOST=hardwarehero.mssql
      - DB_NAME=HardwareHero.AggregatorDb
      - DB_SA_PASSWORD=password@#12345
    depends_on:
      - otel-collector
      - identity.api

  contributor.api:
    container_name: microservice_Contributor-api
    image: ${DOCKER_REGISTRY-}contributorapi
    volumes:
      - ./../Contributor.DataAccess/Scripts:/root/app
    build:
      context: .
      dockerfile: Services/Contributor/Contributor.Api/Dockerfile
    networks:
      - backend
    environment:
      - Otel__Endpoint=http://otel-collector:4317
      - DB_HOST=hardwarehero.mssql
      - DB_NAME=HardwareHero.ContributorDb
      - DB_SA_PASSWORD=password@#12345
    depends_on:
      - otel-collector
      - identity.api

  prices.api:
    container_name: microservice_Prices-api
    image: ${DOCKER_REGISTRY-}pricesapi
    build:
      context: .
      dockerfile: Services/Prices/Prices.Api/Dockerfile
    depends_on:
      - hardwarehero.mongo
      - otel-collector
      - identity.api
    networks:
      - backend
    environment:
      - Otel__Endpoint=http://otel-collector:4317
      - DB_HOST=hardwarehero.mongo
      - DB_NAME=Prices      

  mail.api:
    container_name: microservice_Mail-api
    image: ${DOCKER_REGISTRY-}mailapi
    build:
      context: .
      dockerfile: Services/Mail/Mail.Api/Dockerfile
    depends_on:
      - hardwarehero.mongo
      - otel-collector
      - identity.api
    networks:
      - backend
    environment:
      - Otel__Endpoint=http://otel-collector:4317
      - DB_HOST=hardwarehero.mongo
      - DB_NAME=Mail

  storage.api:
    container_name: microservice_Storage-api
    image: ${DOCKER_REGISTRY-}storageapi
    build:
      context: .
      dockerfile: Services/Storage/Storage.Api/Dockerfile
    depends_on:
      - otel-collector
    networks:
      - backend
    volumes:
      - filedata:/data/files
    environment:
      - Otel__Endpoint=http://otel-collector:4317
      - Storage:BasePath=/data/files
      - Storage:BaseUrl=http://localhost:82/files

  hardwarehero.mongo:
    container_name: database_HardwareHero-mongo
    image: mongo
    ports:
      - 8090:27017
    networks:
      - backend

  hardwarehero.mssql:
    container_name: database_HardwareHero-mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@#12345
    volumes_from:
      - aggregator.api
    networks:
      - backend
    ports:
      - 8080:1433
 
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: message-bus_Zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka1:
    image: confluentinc/cp-kafka
    container_name: message-bus_Kafka-events-1
    ports:
      - "9092:9092"
    networks:
      - backend
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
    depends_on:
      - zookeeper

  kafka2:
    image: confluentinc/cp-kafka
    container_name: message-bus_Kafka-messages-1
    ports:
      - "9082:9082"
    networks:
      - backend
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9082
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: message-bus_Kafka-UI
    ports:
      - 9100:8080
    networks:
      - backend
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9082
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka1
      - kafka2
  
  gateway.ocelot:
    container_name: gateway_Ocelot
    image: ${DOCKER_REGISTRY-}gatewayocelot
    build:
      context: .
      dockerfile: Tools/Gateway/Gateway.Ocelot/Dockerfile
    ports:
      - 8071:80
      - 8070:443
    networks:
      - backend
      # - web_frontend

  configurator.api:
   container_name: microservice_Configurator-api
   image: ${DOCKER_REGISTRY-}configuratorapi
   build:
     context: .
     dockerfile: Services/Configurator/Configurator.Api/Dockerfile
   depends_on:
     - hardwarehero.mongo
     - otel-collector
   networks:
     - backend
   environment:
     - Otel__Endpoint=http://otel-collector:4317
     - DB_HOST=hardwarehero.mongo
     - DB_NAME=Configurator

  users.api:
   container_name: microservice_Users-api
   image: ${DOCKER_REGISTRY-}usersapi
   build:
     context: .
     dockerfile: Services/Identity/Users.Api/Dockerfile
   depends_on:
     - otel-collector
     # - identity.api
   networks:
     - backend
   environment:
     - Otel__Endpoint=http://otel-collector:4317
     - DB_HOST=hardwarehero.mssql
     - DB_NAME=HardwareHero.Users
     - DB_SA_PASSWORD=password@#12345

  identity.api:
   container_name: microservice_Identity-api
   image: ${DOCKER_REGISTRY-}identityapi
   build:
     context: .
     dockerfile: Services/Identity/Identity.Api/Dockerfile
   depends_on:
     - otel-collector
     - users.api
   networks:
     - backend
   environment:
     - Otel__Endpoint=http://otel-collector:4317
     - DB_HOST=hardwarehero.mssql
     - DB_NAME=HardwareHero.IdentityServer
     - DB_SA_PASSWORD=password@#12345
     - SEED=/seed

  ################################## It works but I won't use it cause that eats half of all RAM.

  # elasticsearch:
  #   container_name: logs_els
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
  #   ports:
  #     - 9200:9200
  #   volumes:
  #     - elasticsearch-data:/usr/share/elasticsearch/data
  #   environment:
  #     - xpack.security.enabled=false
  #     - discovery.type=single-node
  #   networks:
  #     - elastic
  #     - backend

  # kibana:
  #   container_name: logs_kibana
  #   image: docker.elastic.co/kibana/kibana:8.14.1
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
  #   environment:
  #     - ELASTICSEARCH_URL=http://els:9200
  #   networks:
  #     - elastic

  ##################################

  otel-collector:
    container_name: monitoring_Otel-collector
    image: otel/opentelemetry-collector:0.95.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_Prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - monitoring
      - backend

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: monitoring_Node-exporter
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss:latest
    container_name: monitoring_Grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring


volumes:
  # elasticsearch-data:
  #   driver: local

  filedata:

  prometheus-data:
    driver: local
  grafana-data:
    driver: local  
  
  shared-scripts:  

