worker_processes 4;

events { worker_connections 1024; }

http {

  server {
    
      listen 82;
      server_name hardwarehero.com;

      location / {
           proxy_pass http://localhost:5021;
           proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection keep-alive;
           proxy_set_header Host $host;
           proxy_cache_bypass $http_upgrade;

           add_header Access-Control-Allow-Origin "*";
           add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
      }
  }
}